name: "CI"

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  biome:
    name: Run Biome CI
    runs-on: ubuntu-latest
    steps:
      - name: Checking out changes
        uses: actions/checkout@v4
        
      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      
      - name: Run Biome
        run: biome ci .

  types:
    name: Check Types
    runs-on: ubuntu-latest
    steps:
      - name: Checking out changes
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: "Running Type Checking"
        run: pnpm tsc

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [biome, types]
    steps:
      - name: Checking out changes
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/npm-shrinkwrap.json', '**/yarn.lock', '**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/npm-shrinkwrap.json', '**/yarn.lock', '**/pnpm-lock.yaml') }}
            
      - name: Install dependencies
        run: pnpm install

      - name: Building Package
        run: pnpm build